version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tw"
s3_bucket = "tw-stack"
region = "eu-central-1"
confirm_changeset = false
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
