Parameters:
  Architecture:
    Type: String
    Default: x86_64
    AllowedValues:
      - x86_64
      - arm64
  MonitoringRecipient:
    Type: String
  ContactName:
    Type: String
  ContactEmail:
    Type: String

AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS stack to import timesheet reports from Clockify and export them to various targets in various formats

Resources:
  ImportFromClockifyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: timesheetwizard-importer
      Architectures:
        - !Ref Architecture
      CodeUri: ../importer
      Handler: not.used.in.provided.runtime
      Runtime: provided.al2
      Environment:
        Variables:
          MICRONAUT_ENVIRONMENTS: aws
      Description: An AWS Lambda function to import timesheets from Clockify
      MemorySize: 256
      PackageType: Zip
      Timeout: 60
      AutoPublishAlias: Live
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3FullAccess
      Tracing: Active
    Metadata:
      BuildMethod: makefile

  GenerateExportsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: timesheetwizard-generate-exports
      Architectures:
        - !Ref Architecture
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Runtime: java17
      CodeUri: ../generate-exports/build/function.zip
      PackageType: Zip
      Environment:
        Variables:
         DISABLE_SIGNAL_HANDLERS: true
         QUARKUS_PROFILE: aws
         CONTACT_NAME: !Ref ContactName
         CONTACT_EMAIL: !Ref ContactEmail
      Description: An AWS Lambda function to generate exports-timesheets
      MemorySize: 512
      Timeout: 60
      AutoPublishAlias: Live
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3FullAccess
      Tracing: PassThrough
      Events:
        JSONFileUpload:
          Type: S3
          Properties:
            Bucket: !Ref TimesheetwizardDataBucket
            Events: s3:ObjectCreated:Put
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: json

  ImportFromClockifyLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn:
      - ImportFromClockifyFunction
    Properties:
      LogGroupName: !Join [ "", [ "/aws/lambda/", !Ref ImportFromClockifyFunction ] ]
      RetentionInDays: 30

  GenerateExportsLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn:
      - GenerateExportsFunction
    Properties:
      LogGroupName: !Join [ "", [ "/aws/lambda/", !Ref GenerateExportsFunction ] ]
      RetentionInDays: 30

  ImportFromClockifyDailyEvent:
    Type: AWS::Events::Rule
    Properties:
      Name: timesheetwizard-importer-daily
      ScheduleExpression: cron(30 17 ? * MON,TUE,WED,THU,FRI *)
      State: ENABLED
      Targets:
        - Arn: !GetAtt ImportFromClockifyFunction.Arn
          Id: timesheetwizard-importer-daily
          Input: '{"body": "{\"customerIds\": [], \"dateRangeType\": \"THIS_MONTH\"}"}'

  ImportFromClockifyMonthlyEvent:
    Type: AWS::Events::Rule
    Properties:
      Name: timesheetwizard-importer-monthly
      ScheduleExpression: cron(0 5 1 * ? *)
      State: ENABLED
      Targets:
        - Arn: !GetAtt ImportFromClockifyFunction.Arn
          Id: timesheetwizard-importer-monthly
          Input: '{"body": "{\"customerIds\": [], \"dateRangeType\": \"LAST_MONTH\"}"}'

  PermissionForImportFromClockifyDailyEvent:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: ImportFromClockifyFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ImportFromClockifyDailyEvent.Arn

  PermissionForImportFromClockifyMonthlyEvent:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: ImportFromClockifyFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ImportFromClockifyMonthlyEvent.Arn

  TimesheetwizardDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: timesheetwizard-data
      AccessControl: Private
      VersioningConfiguration:
        Status: Suspended
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  TimesheetwizardErrorTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Ref MonitoringRecipient
          Protocol: email
      TopicName: timesheetwizard-error-topic

  ImportFromClockifyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: importer-alarm
      ActionsEnabled: true
      OKActions: [ ]
      AlarmActions:
        - Ref: TimesheetwizardErrorTopic
      InsufficientDataActions: [ ]
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Maximum
      Dimensions:
        - Name: FunctionName
          Value: !Ref ImportFromClockifyFunction
      Period: 300
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing

  GenerateExportsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: generate-exports-alarm
      ActionsEnabled: true
      OKActions: [ ]
      AlarmActions:
        - Ref: TimesheetwizardErrorTopic
      InsufficientDataActions: [ ]
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Maximum
      Dimensions:
        - Name: FunctionName
          Value: !Ref GenerateExportsFunction
      Period: 300
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing
