version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/apps/importer"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/apps/documents-generator"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/libs/documents-generator-spi"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/libs/documents-generator-customers-public"
    schedule:
      interval: "daily"
