version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/importer"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/generate-exports"
    schedule:
      interval: "daily"
