version: 2

updates:
  - package-ecosystem: "gradle"
    registries: "*"
    directory: "/."
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
