version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/import-from-clockify"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/generate-excel"
    schedule:
      interval: "daily"
