[extend]
useDefault = true

[[allowlists]]
description = "Well known Azurite testing account key"
regexTarget = "match"
regexes = [
    '''Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=='''
]