spring:
  cloud:
    aws:
      region:
        static: eu-central-1

timesheet-wizard:
  aws:
    enabled: true
  azure:
    enabled: false
  config:
    aws:
      s3:
        bucket: tw-sheets

  export:
    aws:
      s3:
        bucket: tw-sheets