micronaut:
  application:
    name: importer

jackson:
  serialization:
    writeDatesAsTimestamps: false

aws:
  s3:
    bucket: timesheetwizard-data
    region: eu-central-1

clockify:
  reports-url: "https://reports.api.clockify.me"
  api-key: your-api-key
  workspace-id: your-workspace-id

logger:
  levels:
    dev.hertlein.timesheetwizard: DEBUG
