spring:
  application:
    name: Timesheet-Wizard
  main:
    web-application-type: none

jackson:
  serialization:
    writeDatesAsTimestamps: false

micronaut:
  object-storage:
    azure:
      primary:
        container: tw-sheets
        endpoint: ${AZURE_STORAGE_BLOB_ENDPOINT}

timesheet-wizard:
  import:
    clockify:
      reports-url: "https://reports.api.clockify.me/"
      api-key: ${CLOCKIFY_API_KEY}
      workspace-id: ${CLOCKIFY_WORKSPACE_ID}

logging:
  level:
    dev.hertlein.timesheetwizard: DEBUG
