name: Build non-master branch

on:
  pull_request:
  push:
    branches-ignore:
      - 'master'

env:
  JAVA_VERSION: '21'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      - name: Build & test with Gradle
        run: ./gradlew test

      - name: Generate test report (tw-core)
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: generate test report (tw-core)
          path: ./tw-core/build/test-results/test/*.xml
          reporter: java-junit

      - name: Generate test report (tw-app-aws)
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: generate test report (tw-app-aws)
          path: ./tw-app-aws/build/test-results/test/*.xml
          reporter: java-junit

      - name: Generate test report (tw-app-azure)
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: generate test report (tw-app-azure)
          path: ./tw-app-azure/build/test-results/test/*.xml
          reporter: java-junit