name: Cleanup releases
on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          keep_latest: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

